// <auto-generated />
using Esmane_juhiluba.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Esmane_juhiluba.Migrations
{
    [DbContext(typeof(Esmane_juhilubaContext))]
    partial class Esmane_juhilubaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Esmane_juhiluba.Models.Eksam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Eesnimi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Luba")
                        .HasColumnType("int");

                    b.Property<string>("Perenimi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sõidu")
                        .HasColumnType("int");

                    b.Property<int>("Teooria")
                        .HasColumnType("int");

                    b.Property<int>("Tervisekontroll")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Eesnimi", "Perenimi")
                        .IsUnique()
                        .HasFilter("[Eesnimi] IS NOT NULL AND [Perenimi] IS NOT NULL");

                    b.ToTable("Eksam");
                });
#pragma warning restore 612, 618
        }
    }
}
